### PR TITLE
fix(test_user):add test user

### LINKED ISSUE #268: Test user selector for login
We can add a selector to the login so we don't need to list them and take too much space.
https://zpl.io/bzQDneX
login with test user selector

### PR DESCRIPTION
**Pull request by Edgar097**
### Add test users

- Resolve #268 

image

### Steps to test

1. Make run
2. Log In

#### CheckList

- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

### CODE REVIEW

File: webapp/src/components/LoginModal/Login.js [hunk 1]
```diff
@@ -290,9 +333,38 @@ const LoginModal = () => {
...
+                    handleSetFieldSelector(
+                      'account',
+                      event.target.value.toLowerCase().replace(/\s/g, '')
+                    )
+                  }
+                >
+                  <MenuItem value="">
+                    <em>none</em>
+                  </MenuItem>
+                  <MenuItem value={'testuser@ggoods.io'}>Test User</MenuItem>
```
Comment (xavier506) [inline webapp/src/components/LoginModal/Login.js:358]: @adriexnet what do you think?
